name: Build and push to AWS

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: checkout repo
              uses: actions/checkout@v3

            - name: Setup dotnet
              uses: actions/setup-dotnet@v3
              with: 
                dotnet-version: '9.0'

            - name: Build project
              run: dotnet restore; dotnet publish -o site;

            - name: create zip package
              Run: cd site; zip ../site.zip *;

            - name: Deploy to aws EB
              uses: einaregilsson/beanstalk-deploy@v22
              with:
                aws_access_key: ${{ AWS_ACCESS_KEY_ID }}
                aws_secret_key: ${{ AWS_SECRET_ACCESS_KEY }}
                application_name: Kryptering API
                environment_name: KrypteringAPI-env
                version_label: ${{ github.run_id }}
                region: eu-north-1
                deployment_package: site.zip
